[package]
name = "systemd-journal-logger"
version = "0.1.0"
authors = ["Sebastian Wiesner <sebastian@swsnr.de>"]
license = "MIT OR Apache-2.0"
readme = "README.md"
repository = "https://github.com/lunaryorn/systemd-journal-logger.rs"
documentation = "https://docs.rs/systemd-journal-logger"
description = """
Systemd journal logger for the log facade
"""
categories = ["development-tools::debugging"]
keywords = ["logging", "systemd", "journal"]
edition = "2018"

[dependencies]
log = "^0.4"
libsystemd = "^0.3  "

[dev-dependencies]
pretty_assertions = "^0.7"
serde_json = "^1"
rand = "^0.8"

[package.metadata.release]
pre-release-commit-message = "Release {{version}}"
post-release-commit-message = "Bump version to {{next_version}}"
tag-prefix = ""
tag-message = "Version {{tag_name}}"
pre-release-replacements = [
    { file="CHANGELOG.md", search="## \\[Unreleased\\]", replace = "## [Unreleased]\n\n## [{{version}}] – {{date}}", exactly = 1 },
    { file="CHANGELOG.md", search="compare/.+\\.\\.\\.HEAD", replace = "compare/{{tag_name}}...HEAD\n[{{version}}]: https://github.com/lunaryorn/systemd-journal-logger.rs/compare/v{{prev_version}}...{{tag_name}}", exactly = 1 },
]
