name: Test

on:
  push:
    # Don't build tags; that's redundant with pushes to main normally.
    tags-ignore: '*'
    # Only build main, for all other branches rely on pull requests.  This
    # avoids duplicate builds for pull requests.
    branches: main
    # Don't build for trivial changes
    paths-ignore:
      - '*.md'
      - 'LICENSE*'
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # Test against MRSV and stable
        rust: ['1.56.0', 'stable']
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@master
        with:
          components: clippy,rustfmt
          toolchain: ${{ matrix.rust }}
      - run: cargo build --all-targets
      - run: cargo clippy --all-targets
      - run: cargo test
      - run: cargo doc
      - run: cargo fmt -- --check

  cargo-deny:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: EmbarkStudios/cargo-deny-action@v1
