name: Test

on: [push, pull_request]

jobs:
  rustfmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
          components: rustfmt
      - name: rustfmt --check
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: -- --check

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: 'stable'
          override: true
          components: clippy
      - name: cargo build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --all-targets
      - name: cargo clippy
        uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --all-targets

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: 'stable'
          override: true
      - name: cargo test
        uses: actions-rs/cargo@v1
        with:
          command: test

  doc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: 'stable'
          override: true
      - name: cargo doc
        uses: actions-rs/cargo@v1
        with:
          command: doc
